version: '3.3'

services:
  localstack:
    image: docker.io/localstack/localstack:0.13.1
    networks:
      - local
    ports:
      - 4566:4566
    environment:
      - SERVICES=sqs
  
  redis_cluster:
    container_name: redis_cluster
    image: docker.io/grokzen/redis-cluster:6.0.16
    networks:
      - local
    privileged: true
    environment:
      - IP=0.0.0.0
    ports:
      - '7000-7005:7000-7005'

networks:
  local:
