version: '3.3'

services:
  sut:
    build:
      context: .
      dockerfile: ./Dockerfile.test
    environment:
      - SQS_ENDPOINT=http://localstack:4566
    networks:
      - local
    depends_on:
      - localstack
    volumes:
      - ../../..:/code
