name: Native

on:
  push:
    branches: [ mobile-app/init ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Select Latest XCode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Node
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v1
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      # todo get from secrets
      - name: Generate .env file
        run: |
          echo "IDENTITYSERVER_ISSUER=https://identity-server.dev01.devland.is
          IDENTITYSERVER_CLIENT_ID=@island.is-app
          IDENTITYSERVER_SCOPES=openid profile api_resource.scope offline_access
          API_ENDPOINT=https://beta.dev01.devland.is/api
          BUNDLE_ID_IOS=is.island.app-dev
          BUNDLE_ID_ANDROID=is.island.app" > apps/native/app/.env
          cat apps/native/app/.env


      - name: Install Dependencies
        run: yarn install

      - name: Install Native Dependencies
        run: cd apps/native && yarn install

      - name: Symlink Nx Dependencies
        run: |
          rm -rf apps/native/app/node_modules
          mkdir -p apps/native/app/node_modules/{@babel,@nrwl,@react-native-community}
          ln -s "$(pwd)/node_modules/@babel/runtime" "$(pwd)/apps/native/app/node_modules/@babel/runtime"
          ln -s "$(pwd)/node_modules/@react-native-community/cli-platform-ios" "$(pwd)/apps/native/app/node_modules/@react-native-community/cli-platform-ios"
          ln -s "$(pwd)/node_modules/@react-native-community/cli-platform-android" "$(pwd)/apps/native/app/node_modules/@react-native-community/cli-platform-android"
          ln -s "$(pwd)/node_modules/@nrwl/react-native" "$(pwd)/apps/native/app/node_modules/@nrwl/react-native"
          ln -s "$(pwd)/node_modules/hermes-engine" "$(pwd)/apps/native/app/node_modules/hermes-engine"
          ln -s "$(pwd)/node_modules/jsc-android" "$(pwd)/apps/native/app/node_modules/jsc-android"
          ln -s "$(pwd)/node_modules/react-native" "$(pwd)/apps/native/app/node_modules/react-native"

      - name: Update Pods
        run: |
          gem update cocoapods xcodeproj
          cd apps/native/app/ios && pod install

      - run: brew tap wix/brew
      - run: brew install applesimutils
      - run: cd apps/native && yarn detox:build:ios
      - name: Debug info
        run: |
          find apps/native/app/ios/build | grep Info.plist
          cat apps/native/app/ios/build/Build/Products/Release-iphonesimulator/IslandApp.app/Info.plist
          /usr/libexec/PlistBuddy -c "Print" apps/native/app/ios/build/Build/Products/Release-iphonesimulator/IslandApp.app/Info.plist || echo "failure"
      - run: cd apps/native && yarn detox:test:ios

      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: ios-e2e-artifacts
          path: |
            apps/native/app/ios/build/Build/Products/Release-iphonesimulator/IslandApp.app/
            apps/native/app/ios/build/Build/Products/Release-iphonesimulator/IslandApp.app.dSYM/
            apps/native/app-e2e/artifacts/
