
name: Monorepo Nightly

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - qa/ci-acceptance
  workflow_dispatch:
  create:
  pull_request:
    types: [labeled]

defaults:
  run:
    shell: bash

env:
  DOCKER_REGISTRY: 821090935708.dkr.ecr.eu-west-1.amazonaws.com/
  DOCKER_BASE_IMAGE_REGISTRY: 821090935708.dkr.ecr.eu-west-1.amazonaws.com/ecr-public
  SPINNAKER_URL: https://spinnaker-gate.shared.devland.is
  COMPOSE_HTTP_TIMEOUT: 180
  GITHUB_ACTIONS_CACHE_URL: https://cache.dev01.devland.is/
  TEST_ENVIRONMENT: dev

jobs:
  prepare:
    name: Prepare run
    if: ${{ github.event.label.name == 'acceptance test' }} || ${{ github.event.action == 'push' }}
    runs-on: ec2-runners
    container:
      image: public.ecr.aws/m3u4c4h9/island-is/actions-runner-public:latest
    outputs:
      DOCKER_TAG: ${{ steps.last_build.outputs.DOCKER_TAG }}
    env:
      GIT_BRANCH: "main"
      SPINNAKER_WEBHOOK_TOKEN: ${{ secrets.SPINNAKER_WEBHOOK_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Prepare
        id: last_build
        run: |
          ./scripts/ci/00_prepare-base-tags.sh
          echo "::set-output name=DOCKER_TAG::${DOCKER_TAG}"

  runner:
    name: System-e2e Acceptance tests
    runs-on: ec2-runners
    container:
      image: public.ecr.aws/m3u4c4h9/island-is/actions-runner-public:latest
    needs:
      - prepare
    env:
      GIT_BRANCH: "main"
      SPINNAKER_WEBHOOK_TOKEN: ${{ secrets.SPINNAKER_WEBHOOK_TOKEN }}
      DOCKER_TAG: ${{ needs.prepare.outputs.DOCKER_TAG }}
    steps:
      - uses: actions/checkout@v3
      - name: Trigger Acceptance Test deployment
        run: yarn ts scripts/ci/spinnaker.ts

  cleanup:
    name: Cleanup
    runs-on: ec2-runners
    container:
      image: public.ecr.aws/m3u4c4h9/island-is/actions-runner-public:latest
    needs:
      - runner
    if: always()
    steps:
      - uses: actions/github-script@v6
        with:
          stript: |
            github.rest.pull_request.removeLabels({
              pull_request_numbe: context.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["acceptance test"]
            })

