
name: Monorepo Nightly

on:
  schedule:
    - cron: '0 0 * * *'
  push:
  workflow_dispatch:
  create:
  pull_request:

defaults:
  run:
    shell: bash

env:
  DOCKER_REGISTRY: 821090935708.dkr.ecr.eu-west-1.amazonaws.com/
  DOCKER_BASE_IMAGE_REGISTRY: 821090935708.dkr.ecr.eu-west-1.amazonaws.com/ecr-public
  SPINNAKER_URL: https://spinnaker-gate.shared.devland.is
  COMPOSE_HTTP_TIMEOUT: 180
  GITHUB_ACTIONS_CACHE_URL: https://cache.dev01.devland.is/
  TEST_ENVIRONMENT: dev

jobs:
  acceptance-system-e2e:
    name: System-e2e Acceptance tests
    runs-on: ec2-runners
    container:
      image: public.ecr.aws/m3u4c4h9/island-is/actions-runner-public:latest
    if: always()
    needs:
    steps:
      - uses: actions/checkout@v3
      - name: Trigger Acceptance Test deployment
        env:
          GIT_BRANCH: "main"
          SPINNAKER_WEBHOOK_TOKEN: ${{ secrets.SPINNAKER_WEBHOOK_TOKEN }}
        run: yarn ts scripts/ci/spinnaker.ts
